### ISSUE TITLE
Imports for aws aren't working.

### ISSUE THREAD

**Issue by NeuroWinter** [BitTheByte/Domainker#1]
After creating a new virtualenv and installing the requirements using pip, when I run the program I get the following error:

```Traceback (most recent call last):
  File "domainker.py", line 14, in <module>
    from lib.modules.aws import chkaws
  File "/home/neuro/projects/bugbounties/tools/Domainker/lib/modules/aws.py", line 1, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'
```

This is because the correct import statement is:
`from  io import StringIO`

**Comment by BitTheByte** [comment]
Hi @NeuroWinter.

`cStringIO`  got removed from python 3, this tool was built using python 2.7.15 python 3 support isn't ready yet.

Thanks for contacting me
