### ISSUE TITLE
IOError after running python domainker.py

### ISSUE THREAD

**Issue by pratyush-pandey98** [BitTheByte/Domainker#3]
After manually installing Domainker, on the command to run the python script i am getting the Domainker banner followed by the following error report and the termination of the program:

Traceback (most recent call last):
  File "domainker.py", line 23, in <module>
    if(scheduled_update()):
  File "/home/pratyush/Documents/pentest/Domainker/lib/core/updater.py", line 23, in scheduled_update
    last_check = datetime.strptime(open("lib/core/update.sync","r").read().strip(),'%Y-%m-%d').date()
IOError: [Errno 2] No such file or directory: 'lib/core/update.sync'

Need help to solve this error.

![Screenshot from 2019-06-04 21-49-41](https://user-images.githubusercontent.com/41207181/58896047-d6896380-8712-11e9-8e55-bc7283251b86.png)

**Comment by BitTheByte** [comment]
https://github.com/BitTheByte/Domainker/blob/ce442e81ed5194224787f077d39ad9d541cafc94/lib/core/updater.py#L26
The mentioned code line should prevent this issue from happening. However to fix your issue please create this file `lib/core/update.sync` and set it's content to `2000-01-01` and let me know if the problem continues

**Comment by BitTheByte** [comment]
This has been fixed at https://github.com/BitTheByte/Domainker/commit/b449cc9706d613cc0af3c9a34798157c0fe5a483
